-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."delivery_requests" add column "pickup_longtude" float4
--  null;
