-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."businesses" add column "bussiness_profile" text
--  null default 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTygdi26NdE4pjceF7zZsUDZFdBWZtxSUPAYA&usqp=CAU';
