-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."customers" add constraint "customers_email_key" unique ("email");
