-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP TYPE IF EXISTS order_status2;
--
-- CREATE TYPE order_status2 AS ENUM ('new', 'inprogress','ready','dispatched','cancelled','delivered');
