-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."delivery_requests" add column "delivery_status" delivery_status
--  null;
