-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."authentications" alter column "status" set default 'true';
-- alter table "public"."authentications" alter column "status" drop not null;
