-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- CREATE OR REPLACE FUNCTION public.number_of_likes(info_row infos)
-- --  RETURNS bigint
-- --  LANGUAGE sql
-- --  STABLE
-- -- AS $function$
-- -- select count(*) FILTER (WHERE is_like = true) AS likes_count FROM likes WHERE info_id = info_row.id;
-- -- $function$
--
-- CREATE TYPE public.delivery_status AS ENUM (
--     'accepted',
--     'declined',
--     'started',
--     'cancelled',
--     'attempted',
--     'delivered'
--
-- );
