-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."businesses" add column "industry_specific_document" text
--  null;
