-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE "public"."counties" ("county_id" uuid NOT NULL, "county_name" text NOT NULL, PRIMARY KEY ("county_id") );
