-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."businesses" add column "address_name" text
--  null default 'Kenya,Nairobi';
