-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."counties" alter column "county_id" set default gen_random_uuid();
